/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as EconomicCalendarRouteImport } from './routes/economic-calendar'
import { Route as DemoAccountsRouteImport } from './routes/demo-accounts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BugBountyRouteImport } from './routes/bug-bounty'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TbiIndexRouteImport } from './routes/tbi.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as PayoutsIndexRouteImport } from './routes/payouts.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BrandIndexRouteImport } from './routes/brand.index'
import { Route as TbiExploreRouteImport } from './routes/tbi.explore'
import { Route as SuperadminWithdrawalsRouteImport } from './routes/superadmin.withdrawals'
import { Route as SuperadminWalletsRouteImport } from './routes/superadmin.wallets'
import { Route as SuperadminWalletRouteImport } from './routes/superadmin.wallet'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'
import { Route as SuperadminTrtRouteImport } from './routes/superadmin.trt'
import { Route as SuperadminTransactionsRouteImport } from './routes/superadmin.transactions'
import { Route as SuperadminTopSellersRouteImport } from './routes/superadmin.top-sellers'
import { Route as SuperadminTbiRouteImport } from './routes/superadmin.tbi'
import { Route as SuperadminSubscribersRouteImport } from './routes/superadmin.subscribers'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminSearchAnalyticsRouteImport } from './routes/superadmin.search-analytics'
import { Route as SuperadminRrPurchasesRouteImport } from './routes/superadmin.rr-purchases'
import { Route as SuperadminRrRouteImport } from './routes/superadmin.rr'
import { Route as SuperadminRolesRouteImport } from './routes/superadmin.roles'
import { Route as SuperadminRewardsRouteImport } from './routes/superadmin.rewards'
import { Route as SuperadminReviewsRouteImport } from './routes/superadmin.reviews'
import { Route as SuperadminPopupsRouteImport } from './routes/superadmin.popups'
import { Route as SuperadminPayoutsRouteImport } from './routes/superadmin.payouts'
import { Route as SuperadminPartnerRequestsRouteImport } from './routes/superadmin.partner-requests'
import { Route as SuperadminOffersRouteImport } from './routes/superadmin.offers'
import { Route as SuperadminNotificationsRouteImport } from './routes/superadmin.notifications'
import { Route as SuperadminNewsRouteImport } from './routes/superadmin.news'
import { Route as SuperadminLeaderboardsRouteImport } from './routes/superadmin.leaderboards'
import { Route as SuperadminJournalAnalyticsRouteImport } from './routes/superadmin.journal-analytics'
import { Route as SuperadminInboxRouteImport } from './routes/superadmin.inbox'
import { Route as SuperadminFlagsRouteImport } from './routes/superadmin.flags'
import { Route as SuperadminFaqsRouteImport } from './routes/superadmin.faqs'
import { Route as SuperadminDisputesRouteImport } from './routes/superadmin.disputes'
import { Route as SuperadminDemoAccountsRouteImport } from './routes/superadmin.demo-accounts'
import { Route as SuperadminDailyTasksRouteImport } from './routes/superadmin.daily-tasks'
import { Route as SuperadminComplaintsRouteImport } from './routes/superadmin.complaints'
import { Route as SuperadminClaimsRouteImport } from './routes/superadmin.claims'
import { Route as SuperadminChallengePurchasesRouteImport } from './routes/superadmin.challenge-purchases'
import { Route as SuperadminCashbackRouteImport } from './routes/superadmin.cashback'
import { Route as SuperadminBrandsRouteImport } from './routes/superadmin.brands'
import { Route as SuperadminBrandRequestsRouteImport } from './routes/superadmin.brand-requests'
import { Route as SuperadminBlogRouteImport } from './routes/superadmin.blog'
import { Route as SuperadminBacktestRouteImport } from './routes/superadmin.backtest'
import { Route as SuperadminAuditRouteImport } from './routes/superadmin.audit'
import { Route as SuperadminApiKeysRouteImport } from './routes/superadmin.api-keys'
import { Route as SuperadminAnnouncementsRouteImport } from './routes/superadmin.announcements'
import { Route as SuperadminAnalyticsRouteImport } from './routes/superadmin.analytics'
import { Route as SuperadminAffiliatesRouteImport } from './routes/superadmin.affiliates'
import { Route as SuperadminAdsRouteImport } from './routes/superadmin.ads'
import { Route as SuperadminAcademyRouteImport } from './routes/superadmin.academy'
import { Route as SuperadminBugBountyRouteImport } from './routes/superadmin.Bug-bounty'
import { Route as ReviewsCategoryRouteImport } from './routes/reviews.$category'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as PayoutsBrandSlugRouteImport } from './routes/payouts.$brandSlug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as FirmFirmIdRouteImport } from './routes/firm.$firmId'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardTradingPlanRouteImport } from './routes/dashboard.trading-plan'
import { Route as DashboardTradesRouteImport } from './routes/dashboard.trades'
import { Route as DashboardToolsRouteImport } from './routes/dashboard.tools'
import { Route as DashboardTbiRouteImport } from './routes/dashboard.tbi'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRiskRouteImport } from './routes/dashboard.risk'
import { Route as DashboardRewardsRouteImport } from './routes/dashboard.rewards'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardRebetaRouteImport } from './routes/dashboard.rebeta'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOffersRouteImport } from './routes/dashboard.offers'
import { Route as DashboardLeaderboardsRouteImport } from './routes/dashboard.leaderboards'
import { Route as DashboardIntelligenceRouteImport } from './routes/dashboard.intelligence'
import { Route as DashboardEconomicCalendarRouteImport } from './routes/dashboard.economic-calendar'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardClaimsRouteImport } from './routes/dashboard.claims'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardBrandsRouteImport } from './routes/dashboard.brands'
import { Route as DashboardBacktestRouteImport } from './routes/dashboard.backtest'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAiCoachRouteImport } from './routes/dashboard.ai-coach'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard.accounts'
import { Route as DashboardAcademyRouteImport } from './routes/dashboard.academy'
import { Route as BusinessTrustDashboardRouteImport } from './routes/business.trust-dashboard'
import { Route as BusinessJoinRouteImport } from './routes/business.join'
import { Route as BrandTeamRouteImport } from './routes/brand.team'
import { Route as BrandSettingsRouteImport } from './routes/brand.settings'
import { Route as BrandReviewsRouteImport } from './routes/brand.reviews'
import { Route as BrandPayoutsRouteImport } from './routes/brand.payouts'
import { Route as BrandComplaintsRouteImport } from './routes/brand.complaints'
import { Route as BrandChallengesRouteImport } from './routes/brand.challenges'
import { Route as BrandAnnouncementsRouteImport } from './routes/brand.announcements'
import { Route as BrandAnalyticsRouteImport } from './routes/brand.analytics'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as TbiBrandSlugRouteImport } from './routes/tbi.brand.$slug'
import { Route as SuperadminBrandsNewRouteImport } from './routes/superadmin.brands_.new'
import { Route as BusinessOnboardingCategoryRouteImport } from './routes/business.onboarding.$category'
import { Route as PayoutsBrandSlugTransactionTxIdRouteImport } from './routes/payouts.$brandSlug.transaction.$txId'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicCalendarRoute = EconomicCalendarRouteImport.update({
  id: '/economic-calendar',
  path: '/economic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAccountsRoute = DemoAccountsRouteImport.update({
  id: '/demo-accounts',
  path: '/demo-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BugBountyRoute = BugBountyRouteImport.update({
  id: '/bug-bounty',
  path: '/bug-bounty',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TbiIndexRoute = TbiIndexRouteImport.update({
  id: '/tbi/',
  path: '/tbi/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const PayoutsIndexRoute = PayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const TbiExploreRoute = TbiExploreRouteImport.update({
  id: '/tbi/explore',
  path: '/tbi/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminWithdrawalsRoute = SuperadminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminWalletsRoute = SuperadminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminWalletRoute = SuperadminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTrtRoute = SuperadminTrtRouteImport.update({
  id: '/trt',
  path: '/trt',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTransactionsRoute = SuperadminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTopSellersRoute = SuperadminTopSellersRouteImport.update({
  id: '/top-sellers',
  path: '/top-sellers',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTbiRoute = SuperadminTbiRouteImport.update({
  id: '/tbi',
  path: '/tbi',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSubscribersRoute = SuperadminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSearchAnalyticsRoute =
  SuperadminSearchAnalyticsRouteImport.update({
    id: '/search-analytics',
    path: '/search-analytics',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminRrPurchasesRoute = SuperadminRrPurchasesRouteImport.update({
  id: '/rr-purchases',
  path: '/rr-purchases',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRrRoute = SuperadminRrRouteImport.update({
  id: '/rr',
  path: '/rr',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRolesRoute = SuperadminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRewardsRoute = SuperadminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminReviewsRoute = SuperadminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminPopupsRoute = SuperadminPopupsRouteImport.update({
  id: '/popups',
  path: '/popups',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminPayoutsRoute = SuperadminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminPartnerRequestsRoute =
  SuperadminPartnerRequestsRouteImport.update({
    id: '/partner-requests',
    path: '/partner-requests',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminOffersRoute = SuperadminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminNotificationsRoute = SuperadminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminNewsRoute = SuperadminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLeaderboardsRoute = SuperadminLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminJournalAnalyticsRoute =
  SuperadminJournalAnalyticsRouteImport.update({
    id: '/journal-analytics',
    path: '/journal-analytics',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminInboxRoute = SuperadminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFlagsRoute = SuperadminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFaqsRoute = SuperadminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDisputesRoute = SuperadminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDemoAccountsRoute = SuperadminDemoAccountsRouteImport.update({
  id: '/demo-accounts',
  path: '/demo-accounts',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDailyTasksRoute = SuperadminDailyTasksRouteImport.update({
  id: '/daily-tasks',
  path: '/daily-tasks',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminComplaintsRoute = SuperadminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminClaimsRoute = SuperadminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminChallengePurchasesRoute =
  SuperadminChallengePurchasesRouteImport.update({
    id: '/challenge-purchases',
    path: '/challenge-purchases',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SuperadminCashbackRoute = SuperadminCashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBrandsRoute = SuperadminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBrandRequestsRoute = SuperadminBrandRequestsRouteImport.update({
  id: '/brand-requests',
  path: '/brand-requests',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBlogRoute = SuperadminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBacktestRoute = SuperadminBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAuditRoute = SuperadminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminApiKeysRoute = SuperadminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAnnouncementsRoute = SuperadminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAnalyticsRoute = SuperadminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAffiliatesRoute = SuperadminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAdsRoute = SuperadminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAcademyRoute = SuperadminAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminBugBountyRoute = SuperadminBugBountyRouteImport.update({
  id: '/Bug-bounty',
  path: '/Bug-bounty',
  getParentRoute: () => SuperadminRoute,
} as any)
const ReviewsCategoryRoute = ReviewsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ReviewsRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsBrandSlugRoute = PayoutsBrandSlugRouteImport.update({
  id: '/payouts/$brandSlug',
  path: '/payouts/$brandSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LegalRoute,
} as any)
const FirmFirmIdRoute = FirmFirmIdRouteImport.update({
  id: '/firm/$firmId',
  path: '/firm/$firmId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradingPlanRoute = DashboardTradingPlanRouteImport.update({
  id: '/trading-plan',
  path: '/trading-plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradesRoute = DashboardTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsRoute = DashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTbiRoute = DashboardTbiRouteImport.update({
  id: '/tbi',
  path: '/tbi',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRiskRoute = DashboardRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRewardsRoute = DashboardRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRebetaRoute = DashboardRebetaRouteImport.update({
  id: '/rebeta',
  path: '/rebeta',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOffersRoute = DashboardOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardsRoute = DashboardLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntelligenceRoute = DashboardIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEconomicCalendarRoute =
  DashboardEconomicCalendarRouteImport.update({
    id: '/economic-calendar',
    path: '/economic-calendar',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimsRoute = DashboardClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandsRoute = DashboardBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBacktestRoute = DashboardBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiCoachRoute = DashboardAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAcademyRoute = DashboardAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessTrustDashboardRoute = BusinessTrustDashboardRouteImport.update({
  id: '/business/trust-dashboard',
  path: '/business/trust-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessJoinRoute = BusinessJoinRouteImport.update({
  id: '/business/join',
  path: '/business/join',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandTeamRoute = BrandTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => BrandRoute,
} as any)
const BrandSettingsRoute = BrandSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BrandRoute,
} as any)
const BrandReviewsRoute = BrandReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BrandRoute,
} as any)
const BrandPayoutsRoute = BrandPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => BrandRoute,
} as any)
const BrandComplaintsRoute = BrandComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => BrandRoute,
} as any)
const BrandChallengesRoute = BrandChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => BrandRoute,
} as any)
const BrandAnnouncementsRoute = BrandAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => BrandRoute,
} as any)
const BrandAnalyticsRoute = BrandAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BrandRoute,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TbiBrandSlugRoute = TbiBrandSlugRouteImport.update({
  id: '/tbi/brand/$slug',
  path: '/tbi/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminBrandsNewRoute = SuperadminBrandsNewRouteImport.update({
  id: '/brands_/new',
  path: '/brands/new',
  getParentRoute: () => SuperadminRoute,
} as any)
const BusinessOnboardingCategoryRoute =
  BusinessOnboardingCategoryRouteImport.update({
    id: '/business/onboarding/$category',
    path: '/business/onboarding/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayoutsBrandSlugTransactionTxIdRoute =
  PayoutsBrandSlugTransactionTxIdRouteImport.update({
    id: '/transaction/$txId',
    path: '/transaction/$txId',
    getParentRoute: () => PayoutsBrandSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRouteWithChildren
  '/brokers': typeof BrokersRoute
  '/bug-bounty': typeof BugBountyRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo-accounts': typeof DemoAccountsRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/exchanges': typeof ExchangesRoute
  '/faqs': typeof FaqsRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/programs': typeof ProgramsRoute
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/brand/analytics': typeof BrandAnalyticsRoute
  '/brand/announcements': typeof BrandAnnouncementsRoute
  '/brand/challenges': typeof BrandChallengesRoute
  '/brand/complaints': typeof BrandComplaintsRoute
  '/brand/payouts': typeof BrandPayoutsRoute
  '/brand/reviews': typeof BrandReviewsRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/team': typeof BrandTeamRoute
  '/business/join': typeof BusinessJoinRoute
  '/business/trust-dashboard': typeof BusinessTrustDashboardRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai-coach': typeof DashboardAiCoachRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backtest': typeof DashboardBacktestRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/economic-calendar': typeof DashboardEconomicCalendarRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rebeta': typeof DashboardRebetaRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tbi': typeof DashboardTbiRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard/trading-plan': typeof DashboardTradingPlanRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/payouts/$brandSlug': typeof PayoutsBrandSlugRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/reviews/$category': typeof ReviewsCategoryRoute
  '/superadmin/Bug-bounty': typeof SuperadminBugBountyRoute
  '/superadmin/academy': typeof SuperadminAcademyRoute
  '/superadmin/ads': typeof SuperadminAdsRoute
  '/superadmin/affiliates': typeof SuperadminAffiliatesRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/announcements': typeof SuperadminAnnouncementsRoute
  '/superadmin/api-keys': typeof SuperadminApiKeysRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/backtest': typeof SuperadminBacktestRoute
  '/superadmin/blog': typeof SuperadminBlogRoute
  '/superadmin/brand-requests': typeof SuperadminBrandRequestsRoute
  '/superadmin/brands': typeof SuperadminBrandsRoute
  '/superadmin/cashback': typeof SuperadminCashbackRoute
  '/superadmin/challenge-purchases': typeof SuperadminChallengePurchasesRoute
  '/superadmin/claims': typeof SuperadminClaimsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/daily-tasks': typeof SuperadminDailyTasksRoute
  '/superadmin/demo-accounts': typeof SuperadminDemoAccountsRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/faqs': typeof SuperadminFaqsRoute
  '/superadmin/flags': typeof SuperadminFlagsRoute
  '/superadmin/inbox': typeof SuperadminInboxRoute
  '/superadmin/journal-analytics': typeof SuperadminJournalAnalyticsRoute
  '/superadmin/leaderboards': typeof SuperadminLeaderboardsRoute
  '/superadmin/news': typeof SuperadminNewsRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/partner-requests': typeof SuperadminPartnerRequestsRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/popups': typeof SuperadminPopupsRoute
  '/superadmin/reviews': typeof SuperadminReviewsRoute
  '/superadmin/rewards': typeof SuperadminRewardsRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/rr': typeof SuperadminRrRoute
  '/superadmin/rr-purchases': typeof SuperadminRrPurchasesRoute
  '/superadmin/search-analytics': typeof SuperadminSearchAnalyticsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscribers': typeof SuperadminSubscribersRoute
  '/superadmin/tbi': typeof SuperadminTbiRoute
  '/superadmin/top-sellers': typeof SuperadminTopSellersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/trt': typeof SuperadminTrtRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/wallet': typeof SuperadminWalletRoute
  '/superadmin/wallets': typeof SuperadminWalletsRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/tbi/explore': typeof TbiExploreRoute
  '/brand/': typeof BrandIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/tbi/': typeof TbiIndexRoute
  '/business/onboarding/$category': typeof BusinessOnboardingCategoryRoute
  '/superadmin/brands/new': typeof SuperadminBrandsNewRoute
  '/tbi/brand/$slug': typeof TbiBrandSlugRoute
  '/payouts/$brandSlug/transaction/$txId': typeof PayoutsBrandSlugTransactionTxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/brokers': typeof BrokersRoute
  '/bug-bounty': typeof BugBountyRoute
  '/compare': typeof CompareRoute
  '/demo-accounts': typeof DemoAccountsRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/exchanges': typeof ExchangesRoute
  '/faqs': typeof FaqsRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/programs': typeof ProgramsRoute
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/signup': typeof SignupRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/brand/analytics': typeof BrandAnalyticsRoute
  '/brand/announcements': typeof BrandAnnouncementsRoute
  '/brand/challenges': typeof BrandChallengesRoute
  '/brand/complaints': typeof BrandComplaintsRoute
  '/brand/payouts': typeof BrandPayoutsRoute
  '/brand/reviews': typeof BrandReviewsRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/team': typeof BrandTeamRoute
  '/business/join': typeof BusinessJoinRoute
  '/business/trust-dashboard': typeof BusinessTrustDashboardRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai-coach': typeof DashboardAiCoachRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backtest': typeof DashboardBacktestRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/economic-calendar': typeof DashboardEconomicCalendarRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rebeta': typeof DashboardRebetaRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tbi': typeof DashboardTbiRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard/trading-plan': typeof DashboardTradingPlanRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/payouts/$brandSlug': typeof PayoutsBrandSlugRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/reviews/$category': typeof ReviewsCategoryRoute
  '/superadmin/Bug-bounty': typeof SuperadminBugBountyRoute
  '/superadmin/academy': typeof SuperadminAcademyRoute
  '/superadmin/ads': typeof SuperadminAdsRoute
  '/superadmin/affiliates': typeof SuperadminAffiliatesRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/announcements': typeof SuperadminAnnouncementsRoute
  '/superadmin/api-keys': typeof SuperadminApiKeysRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/backtest': typeof SuperadminBacktestRoute
  '/superadmin/blog': typeof SuperadminBlogRoute
  '/superadmin/brand-requests': typeof SuperadminBrandRequestsRoute
  '/superadmin/brands': typeof SuperadminBrandsRoute
  '/superadmin/cashback': typeof SuperadminCashbackRoute
  '/superadmin/challenge-purchases': typeof SuperadminChallengePurchasesRoute
  '/superadmin/claims': typeof SuperadminClaimsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/daily-tasks': typeof SuperadminDailyTasksRoute
  '/superadmin/demo-accounts': typeof SuperadminDemoAccountsRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/faqs': typeof SuperadminFaqsRoute
  '/superadmin/flags': typeof SuperadminFlagsRoute
  '/superadmin/inbox': typeof SuperadminInboxRoute
  '/superadmin/journal-analytics': typeof SuperadminJournalAnalyticsRoute
  '/superadmin/leaderboards': typeof SuperadminLeaderboardsRoute
  '/superadmin/news': typeof SuperadminNewsRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/partner-requests': typeof SuperadminPartnerRequestsRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/popups': typeof SuperadminPopupsRoute
  '/superadmin/reviews': typeof SuperadminReviewsRoute
  '/superadmin/rewards': typeof SuperadminRewardsRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/rr': typeof SuperadminRrRoute
  '/superadmin/rr-purchases': typeof SuperadminRrPurchasesRoute
  '/superadmin/search-analytics': typeof SuperadminSearchAnalyticsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscribers': typeof SuperadminSubscribersRoute
  '/superadmin/tbi': typeof SuperadminTbiRoute
  '/superadmin/top-sellers': typeof SuperadminTopSellersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/trt': typeof SuperadminTrtRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/wallet': typeof SuperadminWalletRoute
  '/superadmin/wallets': typeof SuperadminWalletsRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/tbi/explore': typeof TbiExploreRoute
  '/brand': typeof BrandIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/legal': typeof LegalIndexRoute
  '/payouts': typeof PayoutsIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/tbi': typeof TbiIndexRoute
  '/business/onboarding/$category': typeof BusinessOnboardingCategoryRoute
  '/superadmin/brands/new': typeof SuperadminBrandsNewRoute
  '/tbi/brand/$slug': typeof TbiBrandSlugRoute
  '/payouts/$brandSlug/transaction/$txId': typeof PayoutsBrandSlugTransactionTxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/blog': typeof BlogRoute
  '/brand': typeof BrandRouteWithChildren
  '/brokers': typeof BrokersRoute
  '/bug-bounty': typeof BugBountyRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo-accounts': typeof DemoAccountsRoute
  '/economic-calendar': typeof EconomicCalendarRoute
  '/exchanges': typeof ExchangesRoute
  '/faqs': typeof FaqsRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/programs': typeof ProgramsRoute
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/signup': typeof SignupRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/brand/analytics': typeof BrandAnalyticsRoute
  '/brand/announcements': typeof BrandAnnouncementsRoute
  '/brand/challenges': typeof BrandChallengesRoute
  '/brand/complaints': typeof BrandComplaintsRoute
  '/brand/payouts': typeof BrandPayoutsRoute
  '/brand/reviews': typeof BrandReviewsRoute
  '/brand/settings': typeof BrandSettingsRoute
  '/brand/team': typeof BrandTeamRoute
  '/business/join': typeof BusinessJoinRoute
  '/business/trust-dashboard': typeof BusinessTrustDashboardRoute
  '/dashboard/academy': typeof DashboardAcademyRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/ai-coach': typeof DashboardAiCoachRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backtest': typeof DashboardBacktestRoute
  '/dashboard/brands': typeof DashboardBrandsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/claims': typeof DashboardClaimsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/economic-calendar': typeof DashboardEconomicCalendarRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/leaderboards': typeof DashboardLeaderboardsRoute
  '/dashboard/offers': typeof DashboardOffersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rebeta': typeof DashboardRebetaRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/rewards': typeof DashboardRewardsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tbi': typeof DashboardTbiRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/trades': typeof DashboardTradesRoute
  '/dashboard/trading-plan': typeof DashboardTradingPlanRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/firm/$firmId': typeof FirmFirmIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/payouts/$brandSlug': typeof PayoutsBrandSlugRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/reviews/$category': typeof ReviewsCategoryRoute
  '/superadmin/Bug-bounty': typeof SuperadminBugBountyRoute
  '/superadmin/academy': typeof SuperadminAcademyRoute
  '/superadmin/ads': typeof SuperadminAdsRoute
  '/superadmin/affiliates': typeof SuperadminAffiliatesRoute
  '/superadmin/analytics': typeof SuperadminAnalyticsRoute
  '/superadmin/announcements': typeof SuperadminAnnouncementsRoute
  '/superadmin/api-keys': typeof SuperadminApiKeysRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/backtest': typeof SuperadminBacktestRoute
  '/superadmin/blog': typeof SuperadminBlogRoute
  '/superadmin/brand-requests': typeof SuperadminBrandRequestsRoute
  '/superadmin/brands': typeof SuperadminBrandsRoute
  '/superadmin/cashback': typeof SuperadminCashbackRoute
  '/superadmin/challenge-purchases': typeof SuperadminChallengePurchasesRoute
  '/superadmin/claims': typeof SuperadminClaimsRoute
  '/superadmin/complaints': typeof SuperadminComplaintsRoute
  '/superadmin/daily-tasks': typeof SuperadminDailyTasksRoute
  '/superadmin/demo-accounts': typeof SuperadminDemoAccountsRoute
  '/superadmin/disputes': typeof SuperadminDisputesRoute
  '/superadmin/faqs': typeof SuperadminFaqsRoute
  '/superadmin/flags': typeof SuperadminFlagsRoute
  '/superadmin/inbox': typeof SuperadminInboxRoute
  '/superadmin/journal-analytics': typeof SuperadminJournalAnalyticsRoute
  '/superadmin/leaderboards': typeof SuperadminLeaderboardsRoute
  '/superadmin/news': typeof SuperadminNewsRoute
  '/superadmin/notifications': typeof SuperadminNotificationsRoute
  '/superadmin/offers': typeof SuperadminOffersRoute
  '/superadmin/partner-requests': typeof SuperadminPartnerRequestsRoute
  '/superadmin/payouts': typeof SuperadminPayoutsRoute
  '/superadmin/popups': typeof SuperadminPopupsRoute
  '/superadmin/reviews': typeof SuperadminReviewsRoute
  '/superadmin/rewards': typeof SuperadminRewardsRoute
  '/superadmin/roles': typeof SuperadminRolesRoute
  '/superadmin/rr': typeof SuperadminRrRoute
  '/superadmin/rr-purchases': typeof SuperadminRrPurchasesRoute
  '/superadmin/search-analytics': typeof SuperadminSearchAnalyticsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscribers': typeof SuperadminSubscribersRoute
  '/superadmin/tbi': typeof SuperadminTbiRoute
  '/superadmin/top-sellers': typeof SuperadminTopSellersRoute
  '/superadmin/transactions': typeof SuperadminTransactionsRoute
  '/superadmin/trt': typeof SuperadminTrtRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/superadmin/wallet': typeof SuperadminWalletRoute
  '/superadmin/wallets': typeof SuperadminWalletsRoute
  '/superadmin/withdrawals': typeof SuperadminWithdrawalsRoute
  '/tbi/explore': typeof TbiExploreRoute
  '/brand/': typeof BrandIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/payouts/': typeof PayoutsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/tbi/': typeof TbiIndexRoute
  '/business/onboarding/$category': typeof BusinessOnboardingCategoryRoute
  '/superadmin/brands_/new': typeof SuperadminBrandsNewRoute
  '/tbi/brand/$slug': typeof TbiBrandSlugRoute
  '/payouts/$brandSlug/transaction/$txId': typeof PayoutsBrandSlugTransactionTxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/blog'
    | '/brand'
    | '/brokers'
    | '/bug-bounty'
    | '/compare'
    | '/dashboard'
    | '/demo-accounts'
    | '/economic-calendar'
    | '/exchanges'
    | '/faqs'
    | '/legal'
    | '/login'
    | '/offers'
    | '/programs'
    | '/review'
    | '/reviews'
    | '/signup'
    | '/superadmin'
    | '/articles/$id'
    | '/brand/analytics'
    | '/brand/announcements'
    | '/brand/challenges'
    | '/brand/complaints'
    | '/brand/payouts'
    | '/brand/reviews'
    | '/brand/settings'
    | '/brand/team'
    | '/business/join'
    | '/business/trust-dashboard'
    | '/dashboard/academy'
    | '/dashboard/accounts'
    | '/dashboard/ai-coach'
    | '/dashboard/analytics'
    | '/dashboard/backtest'
    | '/dashboard/brands'
    | '/dashboard/calendar'
    | '/dashboard/claims'
    | '/dashboard/community'
    | '/dashboard/economic-calendar'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboards'
    | '/dashboard/offers'
    | '/dashboard/profile'
    | '/dashboard/rebeta'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/tbi'
    | '/dashboard/tools'
    | '/dashboard/trades'
    | '/dashboard/trading-plan'
    | '/dashboard/wallet'
    | '/firm/$firmId'
    | '/legal/$slug'
    | '/payouts/$brandSlug'
    | '/r/$slug'
    | '/reviews/$category'
    | '/superadmin/Bug-bounty'
    | '/superadmin/academy'
    | '/superadmin/ads'
    | '/superadmin/affiliates'
    | '/superadmin/analytics'
    | '/superadmin/announcements'
    | '/superadmin/api-keys'
    | '/superadmin/audit'
    | '/superadmin/backtest'
    | '/superadmin/blog'
    | '/superadmin/brand-requests'
    | '/superadmin/brands'
    | '/superadmin/cashback'
    | '/superadmin/challenge-purchases'
    | '/superadmin/claims'
    | '/superadmin/complaints'
    | '/superadmin/daily-tasks'
    | '/superadmin/demo-accounts'
    | '/superadmin/disputes'
    | '/superadmin/faqs'
    | '/superadmin/flags'
    | '/superadmin/inbox'
    | '/superadmin/journal-analytics'
    | '/superadmin/leaderboards'
    | '/superadmin/news'
    | '/superadmin/notifications'
    | '/superadmin/offers'
    | '/superadmin/partner-requests'
    | '/superadmin/payouts'
    | '/superadmin/popups'
    | '/superadmin/reviews'
    | '/superadmin/rewards'
    | '/superadmin/roles'
    | '/superadmin/rr'
    | '/superadmin/rr-purchases'
    | '/superadmin/search-analytics'
    | '/superadmin/settings'
    | '/superadmin/subscribers'
    | '/superadmin/tbi'
    | '/superadmin/top-sellers'
    | '/superadmin/transactions'
    | '/superadmin/trt'
    | '/superadmin/users'
    | '/superadmin/wallet'
    | '/superadmin/wallets'
    | '/superadmin/withdrawals'
    | '/tbi/explore'
    | '/brand/'
    | '/dashboard/'
    | '/legal/'
    | '/payouts/'
    | '/superadmin/'
    | '/tbi/'
    | '/business/onboarding/$category'
    | '/superadmin/brands/new'
    | '/tbi/brand/$slug'
    | '/payouts/$brandSlug/transaction/$txId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/blog'
    | '/brokers'
    | '/bug-bounty'
    | '/compare'
    | '/demo-accounts'
    | '/economic-calendar'
    | '/exchanges'
    | '/faqs'
    | '/login'
    | '/offers'
    | '/programs'
    | '/review'
    | '/reviews'
    | '/signup'
    | '/articles/$id'
    | '/brand/analytics'
    | '/brand/announcements'
    | '/brand/challenges'
    | '/brand/complaints'
    | '/brand/payouts'
    | '/brand/reviews'
    | '/brand/settings'
    | '/brand/team'
    | '/business/join'
    | '/business/trust-dashboard'
    | '/dashboard/academy'
    | '/dashboard/accounts'
    | '/dashboard/ai-coach'
    | '/dashboard/analytics'
    | '/dashboard/backtest'
    | '/dashboard/brands'
    | '/dashboard/calendar'
    | '/dashboard/claims'
    | '/dashboard/community'
    | '/dashboard/economic-calendar'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboards'
    | '/dashboard/offers'
    | '/dashboard/profile'
    | '/dashboard/rebeta'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/tbi'
    | '/dashboard/tools'
    | '/dashboard/trades'
    | '/dashboard/trading-plan'
    | '/dashboard/wallet'
    | '/firm/$firmId'
    | '/legal/$slug'
    | '/payouts/$brandSlug'
    | '/r/$slug'
    | '/reviews/$category'
    | '/superadmin/Bug-bounty'
    | '/superadmin/academy'
    | '/superadmin/ads'
    | '/superadmin/affiliates'
    | '/superadmin/analytics'
    | '/superadmin/announcements'
    | '/superadmin/api-keys'
    | '/superadmin/audit'
    | '/superadmin/backtest'
    | '/superadmin/blog'
    | '/superadmin/brand-requests'
    | '/superadmin/brands'
    | '/superadmin/cashback'
    | '/superadmin/challenge-purchases'
    | '/superadmin/claims'
    | '/superadmin/complaints'
    | '/superadmin/daily-tasks'
    | '/superadmin/demo-accounts'
    | '/superadmin/disputes'
    | '/superadmin/faqs'
    | '/superadmin/flags'
    | '/superadmin/inbox'
    | '/superadmin/journal-analytics'
    | '/superadmin/leaderboards'
    | '/superadmin/news'
    | '/superadmin/notifications'
    | '/superadmin/offers'
    | '/superadmin/partner-requests'
    | '/superadmin/payouts'
    | '/superadmin/popups'
    | '/superadmin/reviews'
    | '/superadmin/rewards'
    | '/superadmin/roles'
    | '/superadmin/rr'
    | '/superadmin/rr-purchases'
    | '/superadmin/search-analytics'
    | '/superadmin/settings'
    | '/superadmin/subscribers'
    | '/superadmin/tbi'
    | '/superadmin/top-sellers'
    | '/superadmin/transactions'
    | '/superadmin/trt'
    | '/superadmin/users'
    | '/superadmin/wallet'
    | '/superadmin/wallets'
    | '/superadmin/withdrawals'
    | '/tbi/explore'
    | '/brand'
    | '/dashboard'
    | '/legal'
    | '/payouts'
    | '/superadmin'
    | '/tbi'
    | '/business/onboarding/$category'
    | '/superadmin/brands/new'
    | '/tbi/brand/$slug'
    | '/payouts/$brandSlug/transaction/$txId'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/blog'
    | '/brand'
    | '/brokers'
    | '/bug-bounty'
    | '/compare'
    | '/dashboard'
    | '/demo-accounts'
    | '/economic-calendar'
    | '/exchanges'
    | '/faqs'
    | '/legal'
    | '/login'
    | '/offers'
    | '/programs'
    | '/review'
    | '/reviews'
    | '/signup'
    | '/superadmin'
    | '/articles/$id'
    | '/brand/analytics'
    | '/brand/announcements'
    | '/brand/challenges'
    | '/brand/complaints'
    | '/brand/payouts'
    | '/brand/reviews'
    | '/brand/settings'
    | '/brand/team'
    | '/business/join'
    | '/business/trust-dashboard'
    | '/dashboard/academy'
    | '/dashboard/accounts'
    | '/dashboard/ai-coach'
    | '/dashboard/analytics'
    | '/dashboard/backtest'
    | '/dashboard/brands'
    | '/dashboard/calendar'
    | '/dashboard/claims'
    | '/dashboard/community'
    | '/dashboard/economic-calendar'
    | '/dashboard/intelligence'
    | '/dashboard/leaderboards'
    | '/dashboard/offers'
    | '/dashboard/profile'
    | '/dashboard/rebeta'
    | '/dashboard/referrals'
    | '/dashboard/reviews'
    | '/dashboard/rewards'
    | '/dashboard/risk'
    | '/dashboard/settings'
    | '/dashboard/tbi'
    | '/dashboard/tools'
    | '/dashboard/trades'
    | '/dashboard/trading-plan'
    | '/dashboard/wallet'
    | '/firm/$firmId'
    | '/legal/$slug'
    | '/payouts/$brandSlug'
    | '/r/$slug'
    | '/reviews/$category'
    | '/superadmin/Bug-bounty'
    | '/superadmin/academy'
    | '/superadmin/ads'
    | '/superadmin/affiliates'
    | '/superadmin/analytics'
    | '/superadmin/announcements'
    | '/superadmin/api-keys'
    | '/superadmin/audit'
    | '/superadmin/backtest'
    | '/superadmin/blog'
    | '/superadmin/brand-requests'
    | '/superadmin/brands'
    | '/superadmin/cashback'
    | '/superadmin/challenge-purchases'
    | '/superadmin/claims'
    | '/superadmin/complaints'
    | '/superadmin/daily-tasks'
    | '/superadmin/demo-accounts'
    | '/superadmin/disputes'
    | '/superadmin/faqs'
    | '/superadmin/flags'
    | '/superadmin/inbox'
    | '/superadmin/journal-analytics'
    | '/superadmin/leaderboards'
    | '/superadmin/news'
    | '/superadmin/notifications'
    | '/superadmin/offers'
    | '/superadmin/partner-requests'
    | '/superadmin/payouts'
    | '/superadmin/popups'
    | '/superadmin/reviews'
    | '/superadmin/rewards'
    | '/superadmin/roles'
    | '/superadmin/rr'
    | '/superadmin/rr-purchases'
    | '/superadmin/search-analytics'
    | '/superadmin/settings'
    | '/superadmin/subscribers'
    | '/superadmin/tbi'
    | '/superadmin/top-sellers'
    | '/superadmin/transactions'
    | '/superadmin/trt'
    | '/superadmin/users'
    | '/superadmin/wallet'
    | '/superadmin/wallets'
    | '/superadmin/withdrawals'
    | '/tbi/explore'
    | '/brand/'
    | '/dashboard/'
    | '/legal/'
    | '/payouts/'
    | '/superadmin/'
    | '/tbi/'
    | '/business/onboarding/$category'
    | '/superadmin/brands_/new'
    | '/tbi/brand/$slug'
    | '/payouts/$brandSlug/transaction/$txId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  BlogRoute: typeof BlogRoute
  BrandRoute: typeof BrandRouteWithChildren
  BrokersRoute: typeof BrokersRoute
  BugBountyRoute: typeof BugBountyRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoAccountsRoute: typeof DemoAccountsRoute
  EconomicCalendarRoute: typeof EconomicCalendarRoute
  ExchangesRoute: typeof ExchangesRoute
  FaqsRoute: typeof FaqsRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  ProgramsRoute: typeof ProgramsRoute
  ReviewRoute: typeof ReviewRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SignupRoute: typeof SignupRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  ArticlesIdRoute: typeof ArticlesIdRoute
  BusinessJoinRoute: typeof BusinessJoinRoute
  BusinessTrustDashboardRoute: typeof BusinessTrustDashboardRoute
  FirmFirmIdRoute: typeof FirmFirmIdRoute
  PayoutsBrandSlugRoute: typeof PayoutsBrandSlugRouteWithChildren
  RSlugRoute: typeof RSlugRoute
  TbiExploreRoute: typeof TbiExploreRoute
  PayoutsIndexRoute: typeof PayoutsIndexRoute
  TbiIndexRoute: typeof TbiIndexRoute
  BusinessOnboardingCategoryRoute: typeof BusinessOnboardingCategoryRoute
  TbiBrandSlugRoute: typeof TbiBrandSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economic-calendar': {
      id: '/economic-calendar'
      path: '/economic-calendar'
      fullPath: '/economic-calendar'
      preLoaderRoute: typeof EconomicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-accounts': {
      id: '/demo-accounts'
      path: '/demo-accounts'
      fullPath: '/demo-accounts'
      preLoaderRoute: typeof DemoAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bug-bounty': {
      id: '/bug-bounty'
      path: '/bug-bounty'
      fullPath: '/bug-bounty'
      preLoaderRoute: typeof BugBountyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tbi/': {
      id: '/tbi/'
      path: '/tbi'
      fullPath: '/tbi/'
      preLoaderRoute: typeof TbiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/payouts/': {
      id: '/payouts/'
      path: '/payouts'
      fullPath: '/payouts/'
      preLoaderRoute: typeof PayoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/brand/': {
      id: '/brand/'
      path: '/'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/tbi/explore': {
      id: '/tbi/explore'
      path: '/tbi/explore'
      fullPath: '/tbi/explore'
      preLoaderRoute: typeof TbiExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/withdrawals': {
      id: '/superadmin/withdrawals'
      path: '/withdrawals'
      fullPath: '/superadmin/withdrawals'
      preLoaderRoute: typeof SuperadminWithdrawalsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/wallets': {
      id: '/superadmin/wallets'
      path: '/wallets'
      fullPath: '/superadmin/wallets'
      preLoaderRoute: typeof SuperadminWalletsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/wallet': {
      id: '/superadmin/wallet'
      path: '/wallet'
      fullPath: '/superadmin/wallet'
      preLoaderRoute: typeof SuperadminWalletRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/trt': {
      id: '/superadmin/trt'
      path: '/trt'
      fullPath: '/superadmin/trt'
      preLoaderRoute: typeof SuperadminTrtRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/transactions': {
      id: '/superadmin/transactions'
      path: '/transactions'
      fullPath: '/superadmin/transactions'
      preLoaderRoute: typeof SuperadminTransactionsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/top-sellers': {
      id: '/superadmin/top-sellers'
      path: '/top-sellers'
      fullPath: '/superadmin/top-sellers'
      preLoaderRoute: typeof SuperadminTopSellersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/tbi': {
      id: '/superadmin/tbi'
      path: '/tbi'
      fullPath: '/superadmin/tbi'
      preLoaderRoute: typeof SuperadminTbiRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/subscribers': {
      id: '/superadmin/subscribers'
      path: '/subscribers'
      fullPath: '/superadmin/subscribers'
      preLoaderRoute: typeof SuperadminSubscribersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/search-analytics': {
      id: '/superadmin/search-analytics'
      path: '/search-analytics'
      fullPath: '/superadmin/search-analytics'
      preLoaderRoute: typeof SuperadminSearchAnalyticsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/rr-purchases': {
      id: '/superadmin/rr-purchases'
      path: '/rr-purchases'
      fullPath: '/superadmin/rr-purchases'
      preLoaderRoute: typeof SuperadminRrPurchasesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/rr': {
      id: '/superadmin/rr'
      path: '/rr'
      fullPath: '/superadmin/rr'
      preLoaderRoute: typeof SuperadminRrRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/roles': {
      id: '/superadmin/roles'
      path: '/roles'
      fullPath: '/superadmin/roles'
      preLoaderRoute: typeof SuperadminRolesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/rewards': {
      id: '/superadmin/rewards'
      path: '/rewards'
      fullPath: '/superadmin/rewards'
      preLoaderRoute: typeof SuperadminRewardsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/reviews': {
      id: '/superadmin/reviews'
      path: '/reviews'
      fullPath: '/superadmin/reviews'
      preLoaderRoute: typeof SuperadminReviewsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/popups': {
      id: '/superadmin/popups'
      path: '/popups'
      fullPath: '/superadmin/popups'
      preLoaderRoute: typeof SuperadminPopupsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/payouts': {
      id: '/superadmin/payouts'
      path: '/payouts'
      fullPath: '/superadmin/payouts'
      preLoaderRoute: typeof SuperadminPayoutsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/partner-requests': {
      id: '/superadmin/partner-requests'
      path: '/partner-requests'
      fullPath: '/superadmin/partner-requests'
      preLoaderRoute: typeof SuperadminPartnerRequestsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/offers': {
      id: '/superadmin/offers'
      path: '/offers'
      fullPath: '/superadmin/offers'
      preLoaderRoute: typeof SuperadminOffersRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/notifications': {
      id: '/superadmin/notifications'
      path: '/notifications'
      fullPath: '/superadmin/notifications'
      preLoaderRoute: typeof SuperadminNotificationsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/news': {
      id: '/superadmin/news'
      path: '/news'
      fullPath: '/superadmin/news'
      preLoaderRoute: typeof SuperadminNewsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/leaderboards': {
      id: '/superadmin/leaderboards'
      path: '/leaderboards'
      fullPath: '/superadmin/leaderboards'
      preLoaderRoute: typeof SuperadminLeaderboardsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/journal-analytics': {
      id: '/superadmin/journal-analytics'
      path: '/journal-analytics'
      fullPath: '/superadmin/journal-analytics'
      preLoaderRoute: typeof SuperadminJournalAnalyticsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/inbox': {
      id: '/superadmin/inbox'
      path: '/inbox'
      fullPath: '/superadmin/inbox'
      preLoaderRoute: typeof SuperadminInboxRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/flags': {
      id: '/superadmin/flags'
      path: '/flags'
      fullPath: '/superadmin/flags'
      preLoaderRoute: typeof SuperadminFlagsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/faqs': {
      id: '/superadmin/faqs'
      path: '/faqs'
      fullPath: '/superadmin/faqs'
      preLoaderRoute: typeof SuperadminFaqsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/disputes': {
      id: '/superadmin/disputes'
      path: '/disputes'
      fullPath: '/superadmin/disputes'
      preLoaderRoute: typeof SuperadminDisputesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/demo-accounts': {
      id: '/superadmin/demo-accounts'
      path: '/demo-accounts'
      fullPath: '/superadmin/demo-accounts'
      preLoaderRoute: typeof SuperadminDemoAccountsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/daily-tasks': {
      id: '/superadmin/daily-tasks'
      path: '/daily-tasks'
      fullPath: '/superadmin/daily-tasks'
      preLoaderRoute: typeof SuperadminDailyTasksRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/complaints': {
      id: '/superadmin/complaints'
      path: '/complaints'
      fullPath: '/superadmin/complaints'
      preLoaderRoute: typeof SuperadminComplaintsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/claims': {
      id: '/superadmin/claims'
      path: '/claims'
      fullPath: '/superadmin/claims'
      preLoaderRoute: typeof SuperadminClaimsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/challenge-purchases': {
      id: '/superadmin/challenge-purchases'
      path: '/challenge-purchases'
      fullPath: '/superadmin/challenge-purchases'
      preLoaderRoute: typeof SuperadminChallengePurchasesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/cashback': {
      id: '/superadmin/cashback'
      path: '/cashback'
      fullPath: '/superadmin/cashback'
      preLoaderRoute: typeof SuperadminCashbackRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/brands': {
      id: '/superadmin/brands'
      path: '/brands'
      fullPath: '/superadmin/brands'
      preLoaderRoute: typeof SuperadminBrandsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/brand-requests': {
      id: '/superadmin/brand-requests'
      path: '/brand-requests'
      fullPath: '/superadmin/brand-requests'
      preLoaderRoute: typeof SuperadminBrandRequestsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/blog': {
      id: '/superadmin/blog'
      path: '/blog'
      fullPath: '/superadmin/blog'
      preLoaderRoute: typeof SuperadminBlogRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/backtest': {
      id: '/superadmin/backtest'
      path: '/backtest'
      fullPath: '/superadmin/backtest'
      preLoaderRoute: typeof SuperadminBacktestRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/audit': {
      id: '/superadmin/audit'
      path: '/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof SuperadminAuditRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/api-keys': {
      id: '/superadmin/api-keys'
      path: '/api-keys'
      fullPath: '/superadmin/api-keys'
      preLoaderRoute: typeof SuperadminApiKeysRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/announcements': {
      id: '/superadmin/announcements'
      path: '/announcements'
      fullPath: '/superadmin/announcements'
      preLoaderRoute: typeof SuperadminAnnouncementsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/analytics': {
      id: '/superadmin/analytics'
      path: '/analytics'
      fullPath: '/superadmin/analytics'
      preLoaderRoute: typeof SuperadminAnalyticsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/affiliates': {
      id: '/superadmin/affiliates'
      path: '/affiliates'
      fullPath: '/superadmin/affiliates'
      preLoaderRoute: typeof SuperadminAffiliatesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/ads': {
      id: '/superadmin/ads'
      path: '/ads'
      fullPath: '/superadmin/ads'
      preLoaderRoute: typeof SuperadminAdsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/academy': {
      id: '/superadmin/academy'
      path: '/academy'
      fullPath: '/superadmin/academy'
      preLoaderRoute: typeof SuperadminAcademyRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/Bug-bounty': {
      id: '/superadmin/Bug-bounty'
      path: '/Bug-bounty'
      fullPath: '/superadmin/Bug-bounty'
      preLoaderRoute: typeof SuperadminBugBountyRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/reviews/$category': {
      id: '/reviews/$category'
      path: '/$category'
      fullPath: '/reviews/$category'
      preLoaderRoute: typeof ReviewsCategoryRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/$brandSlug': {
      id: '/payouts/$brandSlug'
      path: '/payouts/$brandSlug'
      fullPath: '/payouts/$brandSlug'
      preLoaderRoute: typeof PayoutsBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof LegalRoute
    }
    '/firm/$firmId': {
      id: '/firm/$firmId'
      path: '/firm/$firmId'
      fullPath: '/firm/$firmId'
      preLoaderRoute: typeof FirmFirmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trading-plan': {
      id: '/dashboard/trading-plan'
      path: '/trading-plan'
      fullPath: '/dashboard/trading-plan'
      preLoaderRoute: typeof DashboardTradingPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trades': {
      id: '/dashboard/trades'
      path: '/trades'
      fullPath: '/dashboard/trades'
      preLoaderRoute: typeof DashboardTradesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools': {
      id: '/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tbi': {
      id: '/dashboard/tbi'
      path: '/tbi'
      fullPath: '/dashboard/tbi'
      preLoaderRoute: typeof DashboardTbiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/risk': {
      id: '/dashboard/risk'
      path: '/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof DashboardRiskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rewards': {
      id: '/dashboard/rewards'
      path: '/rewards'
      fullPath: '/dashboard/rewards'
      preLoaderRoute: typeof DashboardRewardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rebeta': {
      id: '/dashboard/rebeta'
      path: '/rebeta'
      fullPath: '/dashboard/rebeta'
      preLoaderRoute: typeof DashboardRebetaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/offers': {
      id: '/dashboard/offers'
      path: '/offers'
      fullPath: '/dashboard/offers'
      preLoaderRoute: typeof DashboardOffersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboards': {
      id: '/dashboard/leaderboards'
      path: '/leaderboards'
      fullPath: '/dashboard/leaderboards'
      preLoaderRoute: typeof DashboardLeaderboardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intelligence': {
      id: '/dashboard/intelligence'
      path: '/intelligence'
      fullPath: '/dashboard/intelligence'
      preLoaderRoute: typeof DashboardIntelligenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/economic-calendar': {
      id: '/dashboard/economic-calendar'
      path: '/economic-calendar'
      fullPath: '/dashboard/economic-calendar'
      preLoaderRoute: typeof DashboardEconomicCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claims': {
      id: '/dashboard/claims'
      path: '/claims'
      fullPath: '/dashboard/claims'
      preLoaderRoute: typeof DashboardClaimsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brands': {
      id: '/dashboard/brands'
      path: '/brands'
      fullPath: '/dashboard/brands'
      preLoaderRoute: typeof DashboardBrandsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backtest': {
      id: '/dashboard/backtest'
      path: '/backtest'
      fullPath: '/dashboard/backtest'
      preLoaderRoute: typeof DashboardBacktestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-coach': {
      id: '/dashboard/ai-coach'
      path: '/ai-coach'
      fullPath: '/dashboard/ai-coach'
      preLoaderRoute: typeof DashboardAiCoachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/academy': {
      id: '/dashboard/academy'
      path: '/academy'
      fullPath: '/dashboard/academy'
      preLoaderRoute: typeof DashboardAcademyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/trust-dashboard': {
      id: '/business/trust-dashboard'
      path: '/business/trust-dashboard'
      fullPath: '/business/trust-dashboard'
      preLoaderRoute: typeof BusinessTrustDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/join': {
      id: '/business/join'
      path: '/business/join'
      fullPath: '/business/join'
      preLoaderRoute: typeof BusinessJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/team': {
      id: '/brand/team'
      path: '/team'
      fullPath: '/brand/team'
      preLoaderRoute: typeof BrandTeamRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/settings': {
      id: '/brand/settings'
      path: '/settings'
      fullPath: '/brand/settings'
      preLoaderRoute: typeof BrandSettingsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/reviews': {
      id: '/brand/reviews'
      path: '/reviews'
      fullPath: '/brand/reviews'
      preLoaderRoute: typeof BrandReviewsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/payouts': {
      id: '/brand/payouts'
      path: '/payouts'
      fullPath: '/brand/payouts'
      preLoaderRoute: typeof BrandPayoutsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/complaints': {
      id: '/brand/complaints'
      path: '/complaints'
      fullPath: '/brand/complaints'
      preLoaderRoute: typeof BrandComplaintsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/challenges': {
      id: '/brand/challenges'
      path: '/challenges'
      fullPath: '/brand/challenges'
      preLoaderRoute: typeof BrandChallengesRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/announcements': {
      id: '/brand/announcements'
      path: '/announcements'
      fullPath: '/brand/announcements'
      preLoaderRoute: typeof BrandAnnouncementsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/analytics': {
      id: '/brand/analytics'
      path: '/analytics'
      fullPath: '/brand/analytics'
      preLoaderRoute: typeof BrandAnalyticsRouteImport
      parentRoute: typeof BrandRoute
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tbi/brand/$slug': {
      id: '/tbi/brand/$slug'
      path: '/tbi/brand/$slug'
      fullPath: '/tbi/brand/$slug'
      preLoaderRoute: typeof TbiBrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/brands_/new': {
      id: '/superadmin/brands_/new'
      path: '/brands/new'
      fullPath: '/superadmin/brands/new'
      preLoaderRoute: typeof SuperadminBrandsNewRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/business/onboarding/$category': {
      id: '/business/onboarding/$category'
      path: '/business/onboarding/$category'
      fullPath: '/business/onboarding/$category'
      preLoaderRoute: typeof BusinessOnboardingCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts/$brandSlug/transaction/$txId': {
      id: '/payouts/$brandSlug/transaction/$txId'
      path: '/transaction/$txId'
      fullPath: '/payouts/$brandSlug/transaction/$txId'
      preLoaderRoute: typeof PayoutsBrandSlugTransactionTxIdRouteImport
      parentRoute: typeof PayoutsBrandSlugRoute
    }
  }
}

interface BrandRouteChildren {
  BrandAnalyticsRoute: typeof BrandAnalyticsRoute
  BrandAnnouncementsRoute: typeof BrandAnnouncementsRoute
  BrandChallengesRoute: typeof BrandChallengesRoute
  BrandComplaintsRoute: typeof BrandComplaintsRoute
  BrandPayoutsRoute: typeof BrandPayoutsRoute
  BrandReviewsRoute: typeof BrandReviewsRoute
  BrandSettingsRoute: typeof BrandSettingsRoute
  BrandTeamRoute: typeof BrandTeamRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandAnalyticsRoute: BrandAnalyticsRoute,
  BrandAnnouncementsRoute: BrandAnnouncementsRoute,
  BrandChallengesRoute: BrandChallengesRoute,
  BrandComplaintsRoute: BrandComplaintsRoute,
  BrandPayoutsRoute: BrandPayoutsRoute,
  BrandReviewsRoute: BrandReviewsRoute,
  BrandSettingsRoute: BrandSettingsRoute,
  BrandTeamRoute: BrandTeamRoute,
  BrandIndexRoute: BrandIndexRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface DashboardRouteChildren {
  DashboardAcademyRoute: typeof DashboardAcademyRoute
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardAiCoachRoute: typeof DashboardAiCoachRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBacktestRoute: typeof DashboardBacktestRoute
  DashboardBrandsRoute: typeof DashboardBrandsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardClaimsRoute: typeof DashboardClaimsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardEconomicCalendarRoute: typeof DashboardEconomicCalendarRoute
  DashboardIntelligenceRoute: typeof DashboardIntelligenceRoute
  DashboardLeaderboardsRoute: typeof DashboardLeaderboardsRoute
  DashboardOffersRoute: typeof DashboardOffersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRebetaRoute: typeof DashboardRebetaRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardRewardsRoute: typeof DashboardRewardsRoute
  DashboardRiskRoute: typeof DashboardRiskRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTbiRoute: typeof DashboardTbiRoute
  DashboardToolsRoute: typeof DashboardToolsRoute
  DashboardTradesRoute: typeof DashboardTradesRoute
  DashboardTradingPlanRoute: typeof DashboardTradingPlanRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAcademyRoute: DashboardAcademyRoute,
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardAiCoachRoute: DashboardAiCoachRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBacktestRoute: DashboardBacktestRoute,
  DashboardBrandsRoute: DashboardBrandsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardClaimsRoute: DashboardClaimsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardEconomicCalendarRoute: DashboardEconomicCalendarRoute,
  DashboardIntelligenceRoute: DashboardIntelligenceRoute,
  DashboardLeaderboardsRoute: DashboardLeaderboardsRoute,
  DashboardOffersRoute: DashboardOffersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRebetaRoute: DashboardRebetaRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardRewardsRoute: DashboardRewardsRoute,
  DashboardRiskRoute: DashboardRiskRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTbiRoute: DashboardTbiRoute,
  DashboardToolsRoute: DashboardToolsRoute,
  DashboardTradesRoute: DashboardTradesRoute,
  DashboardTradingPlanRoute: DashboardTradingPlanRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LegalRouteChildren {
  LegalSlugRoute: typeof LegalSlugRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalSlugRoute: LegalSlugRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface ReviewsRouteChildren {
  ReviewsCategoryRoute: typeof ReviewsCategoryRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsCategoryRoute: ReviewsCategoryRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

interface SuperadminRouteChildren {
  SuperadminBugBountyRoute: typeof SuperadminBugBountyRoute
  SuperadminAcademyRoute: typeof SuperadminAcademyRoute
  SuperadminAdsRoute: typeof SuperadminAdsRoute
  SuperadminAffiliatesRoute: typeof SuperadminAffiliatesRoute
  SuperadminAnalyticsRoute: typeof SuperadminAnalyticsRoute
  SuperadminAnnouncementsRoute: typeof SuperadminAnnouncementsRoute
  SuperadminApiKeysRoute: typeof SuperadminApiKeysRoute
  SuperadminAuditRoute: typeof SuperadminAuditRoute
  SuperadminBacktestRoute: typeof SuperadminBacktestRoute
  SuperadminBlogRoute: typeof SuperadminBlogRoute
  SuperadminBrandRequestsRoute: typeof SuperadminBrandRequestsRoute
  SuperadminBrandsRoute: typeof SuperadminBrandsRoute
  SuperadminCashbackRoute: typeof SuperadminCashbackRoute
  SuperadminChallengePurchasesRoute: typeof SuperadminChallengePurchasesRoute
  SuperadminClaimsRoute: typeof SuperadminClaimsRoute
  SuperadminComplaintsRoute: typeof SuperadminComplaintsRoute
  SuperadminDailyTasksRoute: typeof SuperadminDailyTasksRoute
  SuperadminDemoAccountsRoute: typeof SuperadminDemoAccountsRoute
  SuperadminDisputesRoute: typeof SuperadminDisputesRoute
  SuperadminFaqsRoute: typeof SuperadminFaqsRoute
  SuperadminFlagsRoute: typeof SuperadminFlagsRoute
  SuperadminInboxRoute: typeof SuperadminInboxRoute
  SuperadminJournalAnalyticsRoute: typeof SuperadminJournalAnalyticsRoute
  SuperadminLeaderboardsRoute: typeof SuperadminLeaderboardsRoute
  SuperadminNewsRoute: typeof SuperadminNewsRoute
  SuperadminNotificationsRoute: typeof SuperadminNotificationsRoute
  SuperadminOffersRoute: typeof SuperadminOffersRoute
  SuperadminPartnerRequestsRoute: typeof SuperadminPartnerRequestsRoute
  SuperadminPayoutsRoute: typeof SuperadminPayoutsRoute
  SuperadminPopupsRoute: typeof SuperadminPopupsRoute
  SuperadminReviewsRoute: typeof SuperadminReviewsRoute
  SuperadminRewardsRoute: typeof SuperadminRewardsRoute
  SuperadminRolesRoute: typeof SuperadminRolesRoute
  SuperadminRrRoute: typeof SuperadminRrRoute
  SuperadminRrPurchasesRoute: typeof SuperadminRrPurchasesRoute
  SuperadminSearchAnalyticsRoute: typeof SuperadminSearchAnalyticsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminSubscribersRoute: typeof SuperadminSubscribersRoute
  SuperadminTbiRoute: typeof SuperadminTbiRoute
  SuperadminTopSellersRoute: typeof SuperadminTopSellersRoute
  SuperadminTransactionsRoute: typeof SuperadminTransactionsRoute
  SuperadminTrtRoute: typeof SuperadminTrtRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminWalletRoute: typeof SuperadminWalletRoute
  SuperadminWalletsRoute: typeof SuperadminWalletsRoute
  SuperadminWithdrawalsRoute: typeof SuperadminWithdrawalsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminBrandsNewRoute: typeof SuperadminBrandsNewRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminBugBountyRoute: SuperadminBugBountyRoute,
  SuperadminAcademyRoute: SuperadminAcademyRoute,
  SuperadminAdsRoute: SuperadminAdsRoute,
  SuperadminAffiliatesRoute: SuperadminAffiliatesRoute,
  SuperadminAnalyticsRoute: SuperadminAnalyticsRoute,
  SuperadminAnnouncementsRoute: SuperadminAnnouncementsRoute,
  SuperadminApiKeysRoute: SuperadminApiKeysRoute,
  SuperadminAuditRoute: SuperadminAuditRoute,
  SuperadminBacktestRoute: SuperadminBacktestRoute,
  SuperadminBlogRoute: SuperadminBlogRoute,
  SuperadminBrandRequestsRoute: SuperadminBrandRequestsRoute,
  SuperadminBrandsRoute: SuperadminBrandsRoute,
  SuperadminCashbackRoute: SuperadminCashbackRoute,
  SuperadminChallengePurchasesRoute: SuperadminChallengePurchasesRoute,
  SuperadminClaimsRoute: SuperadminClaimsRoute,
  SuperadminComplaintsRoute: SuperadminComplaintsRoute,
  SuperadminDailyTasksRoute: SuperadminDailyTasksRoute,
  SuperadminDemoAccountsRoute: SuperadminDemoAccountsRoute,
  SuperadminDisputesRoute: SuperadminDisputesRoute,
  SuperadminFaqsRoute: SuperadminFaqsRoute,
  SuperadminFlagsRoute: SuperadminFlagsRoute,
  SuperadminInboxRoute: SuperadminInboxRoute,
  SuperadminJournalAnalyticsRoute: SuperadminJournalAnalyticsRoute,
  SuperadminLeaderboardsRoute: SuperadminLeaderboardsRoute,
  SuperadminNewsRoute: SuperadminNewsRoute,
  SuperadminNotificationsRoute: SuperadminNotificationsRoute,
  SuperadminOffersRoute: SuperadminOffersRoute,
  SuperadminPartnerRequestsRoute: SuperadminPartnerRequestsRoute,
  SuperadminPayoutsRoute: SuperadminPayoutsRoute,
  SuperadminPopupsRoute: SuperadminPopupsRoute,
  SuperadminReviewsRoute: SuperadminReviewsRoute,
  SuperadminRewardsRoute: SuperadminRewardsRoute,
  SuperadminRolesRoute: SuperadminRolesRoute,
  SuperadminRrRoute: SuperadminRrRoute,
  SuperadminRrPurchasesRoute: SuperadminRrPurchasesRoute,
  SuperadminSearchAnalyticsRoute: SuperadminSearchAnalyticsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminSubscribersRoute: SuperadminSubscribersRoute,
  SuperadminTbiRoute: SuperadminTbiRoute,
  SuperadminTopSellersRoute: SuperadminTopSellersRoute,
  SuperadminTransactionsRoute: SuperadminTransactionsRoute,
  SuperadminTrtRoute: SuperadminTrtRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminWalletRoute: SuperadminWalletRoute,
  SuperadminWalletsRoute: SuperadminWalletsRoute,
  SuperadminWithdrawalsRoute: SuperadminWithdrawalsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminBrandsNewRoute: SuperadminBrandsNewRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface PayoutsBrandSlugRouteChildren {
  PayoutsBrandSlugTransactionTxIdRoute: typeof PayoutsBrandSlugTransactionTxIdRoute
}

const PayoutsBrandSlugRouteChildren: PayoutsBrandSlugRouteChildren = {
  PayoutsBrandSlugTransactionTxIdRoute: PayoutsBrandSlugTransactionTxIdRoute,
}

const PayoutsBrandSlugRouteWithChildren =
  PayoutsBrandSlugRoute._addFileChildren(PayoutsBrandSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  BlogRoute: BlogRoute,
  BrandRoute: BrandRouteWithChildren,
  BrokersRoute: BrokersRoute,
  BugBountyRoute: BugBountyRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoAccountsRoute: DemoAccountsRoute,
  EconomicCalendarRoute: EconomicCalendarRoute,
  ExchangesRoute: ExchangesRoute,
  FaqsRoute: FaqsRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  ProgramsRoute: ProgramsRoute,
  ReviewRoute: ReviewRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  SignupRoute: SignupRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  ArticlesIdRoute: ArticlesIdRoute,
  BusinessJoinRoute: BusinessJoinRoute,
  BusinessTrustDashboardRoute: BusinessTrustDashboardRoute,
  FirmFirmIdRoute: FirmFirmIdRoute,
  PayoutsBrandSlugRoute: PayoutsBrandSlugRouteWithChildren,
  RSlugRoute: RSlugRoute,
  TbiExploreRoute: TbiExploreRoute,
  PayoutsIndexRoute: PayoutsIndexRoute,
  TbiIndexRoute: TbiIndexRoute,
  BusinessOnboardingCategoryRoute: BusinessOnboardingCategoryRoute,
  TbiBrandSlugRoute: TbiBrandSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
